source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CBFormController_Example', :exclusive => true do
  pod "CBFormController", :path => "../"
end

target 'CBFormController_Tests', :exclusive => true do
  pod "CBFormController", :path => "../"

  
end
