source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'CBFormController_Example'  do
  pod "CBFormController", :path => "../"
end

target 'CBFormController_Tests' do
  pod "CBFormController", :path => "../"
end
