//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cameronbell/Documents/dev/Sigvaria/ImmunizeCA-Javelin/src/main/java/ca/ohri/javelin/data/model/City.java
//

//#include "J2ObjC_header.h"

/*#pragma push_macro("INCLUDE_ALL_CaOhriJavelinDataModelCity")
#ifdef RESTRICT_CaOhriJavelinDataModelCity
#define INCLUDE_ALL_CaOhriJavelinDataModelCity 0
#else
#define INCLUDE_ALL_CaOhriJavelinDataModelCity 1
#endif
#undef RESTRICT_CaOhriJavelinDataModelCity

//#if !defined (IJCity_) && (INCLUDE_ALL_CaOhriJavelinDataModelCity || defined(INCLUDE_IJCity))
#define IJCity_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
//#include "java/io/Serializable.h"*/

//@class IOSObjectArray;
#import <MLPAutoCompleteTextField/MLPAutoCompletionObject.h>


@interface IJCity : NSObject <MLPAutoCompletionObject> {
 @public
  NSString *cityId_;
  NSString *name_;
  NSString *region_;
  NSString *country_;
//  jdouble longitude_;
//  jdouble latitude_;
}

#pragma mark Public

- (NSString *)autocompleteString;

- (BOOL)isEqual:(id)object;

+ (IJCity *)getCityWithNSString:(NSString *)id_;

- (NSString *)getCountry;

- (NSString *)getFullName;

- (NSString *)getId;

/*- (jdouble)getLatitude;

- (jdouble)getLongitude;
*/
- (NSString *)getName;

- (NSString *)getRegion;

- (void)setName:(NSString *)name;
- (void)setCityId:(NSString *)cityId;
- (void)setRegion:(NSString *)region;

#pragma mark Protected

- (instancetype)init;

@end
/*
J2OBJC_EMPTY_STATIC_INIT(IJCity)

J2OBJC_FIELD_SETTER(IJCity, cityId_, NSString *)
J2OBJC_FIELD_SETTER(IJCity, name_, NSString *)
J2OBJC_FIELD_SETTER(IJCity, region_, NSString *)
J2OBJC_FIELD_SETTER(IJCity, country_, NSString *)

FOUNDATION_EXPORT void IJCity_init(IJCity *self);

FOUNDATION_EXPORT IJCity *new_IJCity_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IJCity *create_IJCity_init();

FOUNDATION_EXPORT IJCity *IJCity_getCityWithNSString_(NSString *id_);

J2OBJC_TYPE_LITERAL_HEADER(IJCity)

@compatibility_alias CaOhriJavelinDataModelCity IJCity;

#endif

#pragma pop_macro("INCLUDE_ALL_CaOhriJavelinDataModelCity")*/
