//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/cameronbell/Documents/dev/Sigvaria/ImmunizeCA-Javelin/src/main/java/ca/ohri/javelin/data/model/City.java
//

//#include "IOSObjectArray.h"
//#include "J2ObjC_source.h"
//#include "ca/ohri/javelin/data/model/City.h"
//#include "ca/ohri/javelin/data/util/manager/DataManager.h"
//#include "com/squareup/moshi/Json.h"
//#include "java/lang/annotation/Annotation.h"
//#include "java/util/List.h"
#import "City.h"

//inline jlong IJCity_get_serialVersionUID();
#define IJCity_serialVersionUID 1LL
//J2OBJC_STATIC_FIELD_CONSTANT(IJCity, serialVersionUID, jlong)

@implementation IJCity

//J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
    self = [super init];
  return self;
}
//J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)getId {
  return cityId_;
}
- (NSString *)autocompleteString {
    return name_;
}

- (NSString *)getName {
  return name_;
}

- (NSString *)getRegion {
  return region_;
}

- (NSString *)getCountry {
  return country_;
}

- (void)setName:(NSString *)name {
    name_ = name;
}
- (void)setCityId:(NSString *)cityId {
    cityId_ = cityId;
}
- (void)setRegion:(NSString *)region {
    region_ = region;
}


/*- (jdouble)getLongitude {
  return longitude_;
}

- (jdouble)getLatitude {
  return latitude_;
}

- (NSString *)autocompleteString {
  return name_;
}

- (NSString *)getFullName {
  return JreStrcat("$$$", name_, @", ", region_);
}

+ (IJCity *)getCityWithNSString:(NSString *)id_ {
  return IJCity_getCityWithNSString_(id_);
}*/

- (BOOL)isEqual:(id)object {
    return [cityId_ isEqualToString:[(IJCity *)object getId]];
    
  //return [object isKindOfClass:[IJCity class]] && [((NSString *) nil_chk([((IJCity *) nil_chk(((IJCity *) cast_chk(object, [IJCity class])))) getId])) isEqual:cityId_];
}

/*+ (IOSObjectArray *)__annotations_name_ {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComSquareupMoshiJson(@"n") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_region_ {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComSquareupMoshiJson(@"r") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_country_ {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComSquareupMoshiJson(@"c") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_longitude_ {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComSquareupMoshiJson(@"o") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_latitude_ {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComSquareupMoshiJson(@"a") } count:1 type:JavaLangAnnotationAnnotation_class_()];
}*/


/*+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "City", NULL, 0x4, NULL, NULL },
    { "getId", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getRegion", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getCountry", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getLongitude", NULL, "D", 0x1, NULL, NULL },
    { "getLatitude", NULL, "D", 0x1, NULL, NULL },
    { "autocompleteString", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getFullName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getCityWithNSString:", "getCity", "Lca.ohri.javelin.data.model.City;", 0x9, NULL, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = IJCity_serialVersionUID },
    { "cityId_", NULL, 0x1, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "name_", NULL, 0x1, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "region_", NULL, 0x1, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "country_", NULL, 0x1, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "longitude_", NULL, 0x4, "D", NULL, NULL, .constantValue.asLong = 0 },
    { "latitude_", NULL, 0x4, "D", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _IJCity = { 2, "City", "ca.ohri.javelin.data.model", NULL, 0x1, 11, methods, 7, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_IJCity;
}*/

@end

/*void IJCity_init(IJCity *self) {
  NSObject_init(self);
}*/

